granos_basicos/urls.py
from django.contrib import admin
from django.urls import path, include
from monitoreo.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', consulta, name='index-granos-basicos'),
    path('granos-basicos/', include('monitoreo.urls'))
]

monitoreo/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
	path('productores/genero-y-produccion/', genero_produccion, name='genero-y-produccion'),
    path('productores/composicion-familiar/', composicion_familiar, name='composicion-familiar'),

    path('monitoreo/georeferencia/', georeferencia, name='georeferencia'),
    path('monitoreo/caracteristicas-parcela/', caracteristicas_parcela, name='caracteristicas-parcela'),
    path('monitoreo/ciclo-productivo/', ciclo_productivo, name='ciclo-productivo'),
    path('monitoreo/uso-suelo/', uso_suelo, name='uso-suelo'),
    path('monitoreo/recursos-economicos/', recursos_economicos, name='recursos-economicos'),
    path('monitoreo/rendimiento/', rendimiento, name='rendimiento'),

    path('ajax/comunies/', get_comunies, name='get-comunies'),
]

lugar/models.py
# -*- coding: UTF-8 -*-

from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=200)
    codigo = models.CharField(max_length=2,
                help_text='Código de 2 letras del país, ejemplo : Nicaragua (ni)')

    class Meta:
        verbose_name_plural = "Países"

    def __str__(self):
        return self.nombre

class Departamento(models.Model):
    # id = models.IntegerField("Código", primary_key=True)
    pais = models.ForeignKey(Pais,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(editable = False,unique=True, null=True, help_text="Usado como url unica(autorellenado)")
    extension = models.DecimalField("Extension Territorial", max_digits=10, decimal_places=2,null=True, blank=True)
    latitud = models.FloatField('Latitud', blank=True, null=True)
    longitud = models.FloatField('Longitud', blank=True, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Departamentos"
        ordering = ['nombre']

class Municipio(models.Model):
    # id = models.IntegerField("Código", primary_key=True)
    departamento = models.ForeignKey(Departamento,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(editable = False,unique=True, null=True, help_text="Usado como url unica(autorellenado)")
    extension = models.DecimalField("Extension Territorial", max_digits=10, decimal_places=2, blank=True, null=True)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.departamento.nombre, self.nombre)

    class Meta:
        verbose_name_plural = "Municipios"
        ordering = ['departamento__nombre', 'nombre']

class Comunidad(models.Model):
    municipio = models.ForeignKey(Municipio,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)

    class Meta:
        verbose_name_plural="Comunidades"
        ordering = ['nombre']

    def __str__(self):
        return u'%s' % self.nombre

mapeo/models.py
from django.db import models
from django.utils.translation import gettext as _
from lugar.models import *
from sorl.thumbnail import ImageField
from monitoreo.utils import *
from ckeditor.fields import RichTextField
from colorfield.fields import ColorField

# Create your models here.

class Sector(models.Model):
	nombre  = models.CharField(max_length=200)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = (u'Sector')
		verbose_name_plural = (u'Sectores')

class AreaAccion(models.Model):
	nombre = models.CharField(_(u'Nombre'), max_length=250)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = _(u'Area de Acción')
		verbose_name_plural = _(u'Areas de Acción')

class SitioAccion(models.Model):
	nombre = models.CharField(_(u'Nombre'), max_length=250)
	area_accion = models.ForeignKey(AreaAccion,on_delete=models.CASCADE)
	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = _(u'Sitio de Acción')
		verbose_name_plural = _(u'Sitios de Acción')

class Plataforma(models.Model):
	nombre = models.CharField(_(u'Nombre'), max_length=250)
	sitio_accion = models.ForeignKey(SitioAccion,on_delete=models.CASCADE)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = _(u'Plataforma')
		verbose_name_plural = _(u'Plataformas')		

class Sector_en(models.Model):
	nombre  = models.CharField(max_length=200,verbose_name='Name')

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name = (u'Sector')
		verbose_name_plural = (u'Sectors')

class Organizaciones(models.Model):
    nombre = models.CharField(_(u'Nombre'), max_length=200)
    siglas = models.CharField(_(u"Siglas o nombre corto"),
                                help_text=_(u"Siglas o nombre corto de la oganización"),
                                max_length=200)
    area_accion = models.ForeignKey(AreaAccion,on_delete=models.CASCADE)
    sitio_accion = models.ForeignKey(SitioAccion,on_delete=models.CASCADE)
    plataforma = models.ForeignKey(Plataforma,on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector,verbose_name=_(u'Sector (Español)'),on_delete=models.CASCADE)
    sector_en = models.ForeignKey(Sector_en,verbose_name=_(u'Sector (Ingles)'),null=True, blank=True,on_delete=models.CASCADE)
    telefono = models.IntegerField(_(u'Telefono'), null=True, blank=True)
    fax = models.CharField(max_length=50, null=True, blank=True)
    logo = ImageField(upload_to=get_file_path, null=True, blank=True)
    direccion = models.TextField(_(u'Direccion'), null=True, blank=True)

    pais = models.ForeignKey(Pais,on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento,on_delete=models.CASCADE,null=True, blank=True)
    municipio = models.ForeignKey(Municipio,on_delete=models.CASCADE,null=True, blank=True)
    fundacion = models.CharField(_(u'Año de fundación'),max_length=200,blank=True, null=True)
    temas = RichTextField(_(u'Temas'), blank=True, null=True)
    generalidades = RichTextField(_(u'Generalidades'), blank=True, null=True)
    contacto = models.CharField(_(u'Persona de contacto'), max_length=200, blank=True, null=True)
    correo_electronico = models.EmailField(_(u'Correo'), null=True, blank=True)
    telefono = models.CharField(_(u'Telefono'), max_length=200, blank=True, null=True)
    sitio_web = models.URLField(_(u'Sitio web'), blank=True, null=True)
    rss = models.CharField(max_length=200, blank=True, null=True)
    font_color = ColorField(blank=True, unique=True)

    fileDir = 'organizaciones/logos/'

    class Meta:
        verbose_name_plural = _(u"Organizaciones")
        unique_together = ("font_color", "nombre")
        ordering = ['nombre',]

    def __str__(self):
        return self.siglas

CHOICE_SEXO = ((1,_(u'Hombre')),(2,_(u'Mujer')))
CHOICE_SEXO_JEFE = ((1,_(u'Hombre')),(2,_(u'Mujer')),(3,_(u'Compartida')))
CHOICE_RANGO = (
                (1, '18 - 25'),
                (2, '26 - 45'),
                (3, '46 - 65'),
                (4, 'Más de 65')
            )

CHOICE_NIVEL_EDUCATIVO = (
                (1, _(u'No sabe leer o escribir')),
                (2, _(u'Primaria Incompleta')),
                (3, _(u'Primaria Completa')),
                (4, _(u'Secundaria Incompleta')),
                (5, _(u'Bachiller')),
                (6, _(u'Universitario')),
            )

CHOICE_TIPO_PERSONA = (
                (1, _(u'Productor o Productora')),
                (2, _(u'Líder o Lideresa comunitaria')),
                (3, _(u'Técnico')),
                (4, _(u'Especialista')),
                (5, _(u'Investigador')),
                (6, _(u'Decisor')),
            )

CHOICE_TIPOLOGIA = (
                (1, _(u'Pequeño campesino de montaña')),
                (2, _(u'Pequeño campesino diversificado')),
                (3, _(u'Finquero cacaotero')),
                (4, _(u'Finquero ganadero cacaotero')),
                (5, _(u'Finquero cafetalero')),
                (6, _(u'Finquero ganadero cafetalero')),
                (7, _(u'Finquero ganadero')),
            )

class Temas(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tema del proyecto/biblioteca'
        verbose_name_plural = 'Temas de los proyectos/bibliotecas'

class TiposProyectos(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Tipo del proyecto'
        verbose_name_plural = 'Tipos de los proyectos'

class Proyectos(models.Model):
    nombre = models.CharField(max_length=250)
    corto = models.CharField(_(u"Nombre corto"),max_length=250)
    codigo = models.CharField(max_length=50)
    inicio = models.DateField(_(u"Fecha de inicio"))
    finalizacion = models.DateField(_(u"Fecha de finalización"))
    descripcion = models.TextField('Descripción del proyecto', null=True, blank=True)
    tipo = models.ForeignKey(TiposProyectos, verbose_name='Tipo proyecto', null=True, blank=True,on_delete=models.CASCADE)
    temas = models.ManyToManyField(Temas, blank=True)
    encargado = models.CharField('Encargado del proyecto', max_length=250, null=True, blank=True)
    alianza = models.ManyToManyField(Plataforma, verbose_name=_(u"Alianza de influencia"))
    influencia = models.ManyToManyField(Municipio, verbose_name=_(u"Zona de influencia"))
    ejecutora = models.ForeignKey(Organizaciones, verbose_name=_(u"Organización ejecutora"),on_delete=models.CASCADE)
    socias = models.ManyToManyField(Organizaciones, related_name="socias", verbose_name=_(u"Organización socias"))
    informacion = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.corto

    class Meta:
        verbose_name_plural = _(u"Proyectos")

class TimeLineProyecto(models.Model):
    proyecto = models.ForeignKey(Proyectos,on_delete=models.CASCADE)
    fecha = models.DateField()
    texto = models.CharField(max_length=100)

    year = models.IntegerField(editable=False)
    mes = models.IntegerField(editable=False)

    def save(self):
        self.year = self.fecha.year
        self.mes = self.fecha.month
        super(TimeLineProyecto, self).save()

    def __str__(self):
        return u'%s - %s ' % (self.proyecto.corto, self.proyecto.codigo)

CHOICE_RANGO = (
				(1, '18 - 25'),
				(2, '26 - 45'),
				(3, '46 - 65'),
				(4, 'Más de 65')
			)
class Persona(models.Model):
	tipo_persona = models.IntegerField(choices=CHOICE_TIPO_PERSONA, null=True, blank=True)
	nombre = models.CharField(_(u'Nombre de la persona'), max_length=200)
	cedula = models.CharField(_(u'cedula de la persona'), max_length=200, null=True, blank=True)
	sexo = models.IntegerField(_(u'Sexo'), choices=CHOICE_SEXO)
	edad = models.IntegerField(_(u'Edad'), choices=CHOICE_RANGO)
	#finca = models.CharField(_(u'Nombre de Finca'), max_length=200, null=True, blank=True)
	pais = models.ForeignKey(Pais,on_delete=models.CASCADE)
	departamento = models.ForeignKey(Departamento,on_delete=models.CASCADE)
	municipio = models.ForeignKey(Municipio,on_delete=models.CASCADE)
	comunidad = models.ForeignKey(Comunidad,on_delete=models.CASCADE)
	#organizacion = models.ManyToManyField(Organizaciones, related_name ="org",
										#verbose_name=_(u'Organizaciones que lo apoyan'))
	#nivel_educacion = models.IntegerField(_(u'Nivel de educacion'), choices=CHOICE_NIVEL_EDUCATIVO)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural= _(u'Personas registradas')

class RubrosAgropecuarios(models.Model):
	nombre = models.CharField(max_length=250)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = _(u'Rubros agropecuarios')

class RubrosNoAgropecuarios(models.Model):
	nombre = models.CharField(max_length=250)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = _(u'Rubros no agropecuarios')

class FuenteManoObra(models.Model):
	nombre = models.CharField(max_length=250)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = _(u'Fuentes de mano de obra')

class FormaAtencion(models.Model):
	nombre = models.CharField(max_length=250)

	def __str__(self):
		return self.nombre

	class Meta:
		verbose_name_plural = _(u'Formas en que atiende')

class Productor(models.Model):
	persona = models.ForeignKey(Persona,on_delete=models.CASCADE)
	fecha = models.DateField()
	finca = models.CharField(_(u'Nombre de Finca'), max_length=200, null=True, blank=True)
	organizacion = models.ManyToManyField(Organizaciones, related_name ="organizacion",
										verbose_name=_(u'Organizaciones que lo apoyan'), blank=True)
	tamano = models.FloatField(_(u'Tamaño de la finca'), null=True, blank=True)
	ganado = models.IntegerField(_(u'Número de ganado'), null=True, blank=True)
	rubros_agro = models.ManyToManyField(RubrosAgropecuarios, related_name="uno", verbose_name=_(u'Rubros que generan ingreso agropecuario'), blank=True)

templates/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Guía Granos Básicos</title>
  <!-- Bootstrap CSS -->
  <link href="/static/general/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="/static/general/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="/static/cacao.css" rel="stylesheet" type="text/css">
</head>

<body>
   <!-- <div class="bar-title">
        <div class="container">
            <div class="row">
                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                    <h3>Alianza CAC</h3>
                </div>
                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">

                </div>
            </div>
        </div>
    </div>-->
    <nav class="navbar navbar-cacao" role="navigation">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Guía granos básicos</a>
            </div>


            <div class="collapse navbar-collapse navbar-ex1-collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/granos-basicos">Consulta</a></li>
                    <li><a href="/admin">Administración</a></li>
                    <!--<li><a href="/admin/logout"></a></li>-->

                </ul>
            </div>
        </div>
    </nav>


    {% block contenido %}{% endblock contenido %}


  <!-- jQuery -->
  <script src="/static/general/js/jQuery/jquery-2.1.1.min.js"></script>
  <script src="/static/general/js/jQuery/jquery-migrate-1.2.1.min.js"></script>

  <!-- Bootstrap -->
  <script src="/static/general/bootstrap/js/bootstrap.min.js"></script>
  <script src="{% static 'analisis/js/highcharts.js' %}"></script>
  <script src="{% static 'analisis/js/exporting.js' %}"></script>
  <script type="text/javascript">
    // var ficha = window.location.pathname.split('/');
    //
    // if (ficha[2]=="sombra") {
    //     $( "#sombra" ).addClass( "in" );
    //     $( "#poda" ).removeClass( "in" );
    // }else {
    //     $( "#poda" ).addClass( "in" );
    //     $( "#sombra" ).removeClass( "in" );
    // };
  </script>
  {% block extra_js %}{% endblock extra_js %}

</body>

</html>

templates/consulta.html
{% extends "base.html" %}

{% block contenido %}
<div class="container hola">
    <div class="title-consulta">
        <h4><i class="fa fa-filter" aria-hidden="true"></i> Filtro</h4>
    </div>
    <div class="filtro">
        <div class="row">
            <form  action="." method="POST"> {% csrf_token %}
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                            <label for="">{{form.year.label}}</label>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8">
                            {{form.year}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                            <label for="">{{form.rubro.label}}</label>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8">
                            {{form.rubro}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                            <label for="">{{form.ciclo.label}}</label>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8">
                            {{form.ciclo}}
                        </div>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                            <label for="">{{form.municipio.label}}</label>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8">
                            {{form.municipio}}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                            <label for="">{{form.comunidad.label}}</label>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8">
                            {{form.comunidad}}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                            <label for="">{{form.organizacion.label}}</label>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8">
                            {{form.organizacion}}
                        </div>
                    </div>
                </div>
                <input type="submit" value="Consultar" class="btn btn-form" name="Consulta"/>
            </form>
        </div>
    </div>
</div>
{% if centinela == 1%}
<style type="text/css">
    .hola{display: none}
</style>
<div class="container">
    <div class="indicadores">
        <div class="title-consulta">
            <h4><i class="fa fa-bars" aria-hidden="true"></i> Indicadores</h4>
        </div>
        <div class="enlaces">
            <div class="row">
                {% include "menu_salidas.html" %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block extra_js %}
<link rel="stylesheet" href="/static/granos_basicos/css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="/static/granos_basicos/js/bootstrap-multiselect.js"></script>
<script type="text/javascript">
  $("select").addClass("form-control");
  $(document).ready(function() {

    $('#id_organizacion').multiselect({
        buttonWidth: '250px',
        includeSelectAllOption: true,
        selectAllText: 'Seleccionar todos',
        buttonText: function(options, select) {
                if (options.length === 0) {
                    return 'Sin selección ...';
                }
                else if (options.length > 3) {
                    return 'Varias opciones seleccionadas!';
                }
                 else {
                     var labels = [];
                     options.each(function() {
                         if ($(this).attr('label') !== undefined) {
                             labels.push($(this).attr('label'));
                         }
                         else {
                             labels.push($(this).html());
                         }
                     });
                     return labels.join(', ') + '';
                 }
            }
    });

      $('#id_municipio').multiselect({
          buttonWidth: '250px',
          includeSelectAllOption: true,
          selectAllText: 'Seleccionar todos',
          buttonText: function(options, select) {
                  if (options.length === 0) {
                      return 'Sin selección ...';
                  }
                  else if (options.length > 3) {
                      return 'Varias opciones seleccionadas!';
                  }
                   else {
                       var labels = [];
                       options.each(function() {
                           if ($(this).attr('label') !== undefined) {
                               labels.push($(this).attr('label'));
                           }
                           else {
                               labels.push($(this).html());
                           }
                       });
                       return labels.join(', ') + '';
                   }
              }
      });

      $('#id_comunidad').multiselect({
          enableCollapsibleOptGroups: true,
          buttonWidth: '250px',
          includeSelectAllOption: true,
          selectAllText: 'Seleccionar todos',
          buttonText: function(options, select) {
                  if (options.length === 0) {
                      return 'Sin selección ...';
                  }
                  else if (options.length > 3) {
                      return 'Varias opciones seleccionadas!';
                  }
                   else {
                       var labels = [];
                       options.each(function() {
                           if ($(this).attr('label') !== undefined) {
                               labels.push($(this).attr('label'));
                           }
                           else {
                               labels.push($(this).html());
                           }
                       });
                       return labels.join(', ') + '';
                   }
              }
      });
      $("#id_comunidad").multiselect('disable');

      var foo2 = [];
      $(document).on('change','#id_municipio',function(){
          $('#id_municipio :selected').each(function(i, selected){
              foo2[i] = $(selected).val();
          });
          $.getJSON('/granos-basicos/ajax/comunies/?ids='+foo2.join(","), function(data){
              var comunidad = $('#id_comunidad')
              comunidad.html('');
              comunidad.multiselect('enable');
              if(data){
                  $.each(data, function(i, item){
                    var group = $('<optgroup></optgroup>').attr('label', i);
                    $.each(item, function(j, item1){
                        group.append($('<option></option>').val(item1.id).html(item1.nombre));
                    });
                    group.appendTo(comunidad);
                    comunidad.multiselect('rebuild');
                  });
             }
         });
      });
    });
</script>
{% endblock %}

templates/menu_salidas.html
<style media="screen">
a[disabled=disabled] {
  pointer-events: none;
  cursor: default;
  color: #CCC;
  font-weight: bold;
}
</style>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
    <ul class="ind">
        <li class="list-header">PRODUCTORES</li>
        <li> <a href="/granos-basicos/productores/genero-y-produccion/"> Genero y Producción de granos básicos</a></li>
        <li><a href="/granos-basicos/productores/composicion-familiar/"> Composición Familiar</a></li>
    </ul>
</div>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
    <ul class="ind">
        <li class="list-header">MONITOREOS</li>
        <li> <a href="/granos-basicos/monitoreo/georeferencia/"> Georeferencia</a></li>
        <li><a href="/granos-basicos/monitoreo/caracteristicas-parcela/"> Características de la parcela</a></li>
        <li><a href="/granos-basicos/monitoreo/ciclo-productivo/"> Ciclo Productivo</a></li>
        <li><a href="/granos-basicos/monitoreo/uso-suelo/"> Uso del Suelo</a></li>
        <li><a href="/granos-basicos/monitoreo/recursos-economicos"> Recursos Económicos</a></li>
        <li><a href="/granos-basicos/monitoreo/rendimiento"> Rendimiento</a></li>
    </ul>
</div>

templates/menu_salidas_indicadores.html
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default panel-ind">
        <a class="panel-heading" role="tab" data-toggle="collapse" data-parent="#accordion" href="#productores" aria-expanded="true" aria-controls="productores"id="headingOne">
            <h4 class="panel-title">
                Productores
            </h4>
        </a>
        <div id="productores" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body menu-">
                <ul class="list-group">

                    <a class="list-group-item" href="/granos-basicos/productores/genero-y-produccion/">
                        Genero y Producción de granos básicos
                    </a>

                    <a class="list-group-item" href="/granos-basicos/productores/composicion-familiar/">
                        Composición Familiar
                    </a>
                </ul>
            </div>
        </div>
    </div>

</div>


<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default panel-ind">
        <a class="panel-heading" role="tab" data-toggle="collapse" data-parent="#accordion" href="#monitoreo" aria-expanded="true" aria-controls="monitoreo" id="headingOne">
            <h4 class="panel-title">
                Monitoreos
            </h4>
        </a>
        <div id="monitoreo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body menu-">
                <ul class="list-group">

                    <a class="list-group-item" href="/granos-basicos/monitoreo/georeferencia/">
                        Georeferencia
                    </a>

                    <a class="list-group-item" href="/granos-basicos/monitoreo/caracteristicas-parcela/">
                        Características de la parcela
                    </a>

                    <a class="list-group-item" href="/granos-basicos/monitoreo/ciclo-productivo/">
                        Ciclo Productivo
                    </a>

                    <a class="list-group-item" href="/granos-basicos/monitoreo/uso-suelo/">
                        Uso del Suelo
                    </a>

                    <a class="list-group-item" href="/granos-basicos/monitoreo/recursos-economicos">
                        Recursos Económicos
                    </a>

                    <a class="list-group-item" href="/granos-basicos/monitoreo/rendimiento">
                        Rendimiento
                    </a>
                </ul>
            </div>
        </div>
    </div>

</div>